package org.smxknife.axis.server.services.impl;

import lombok.extern.slf4j.Slf4j;
import org.smxknife.axis.server.model.User;
import org.smxknife.axis.server.services.UserService;
import org.smxknife.axis.server.util.XmlUtil;

import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Random;

/**
 * @author smxknife
 * 2019/10/18
 */
@Slf4j
public class UserServiceImpl implements UserService {

	private static final Random RANDOM = new Random(10);

	@Override
	public String userInfo(String name) {
		log.info("{} ：入参 - name = {}", this.getClass().getCanonicalName(), name);
		User user = new User();
		user.setName(name);
		user.setSex(random() ? "男" : "女");
		user.setTall(RANDOM.nextFloat());
		user.setWeight(RANDOM.nextFloat());
		return XmlUtil.makeXML("userInfo", user.toMap());
//		log.info("{} : 返回 - {}", this.getClass().getCanonicalName(), xml);
//		return "<soap:Envelope xmlns:soap=\"http://schemas.xmlsoap.org/soap/envelope/\">\n" +
//				"   <soap:Body>\n" +
//				"      <ns2:getGaugeDataResponse xmlns:ns2=\"http://ws.travelsky.com/\">\n" +
//				"         <return>\n" +
//				"            <META>\n" +
//				"               <DTTM>20191022160238</DTTM>\n" +
//				"               <SEQN>123</SEQN>\n" +
//				"               <SNDR>POMS</SNDR>\n" +
//				"               <TYPE>DICTIONARY</TYPE>\n" +
//				"            </META>\n" +
//				"            <RESPONSE_MSG>\n" +
//				"               <MESSAGE>请求成功</MESSAGE>\n" +
//				"               <STATUS_CODE>1000</STATUS_CODE>\n" +
//				"            </RESPONSE_MSG>\n" +
//				"            <SEMS>\n" +
//				"               <AREA>\n" +
//				"                  <AREA_DESC>航站楼总滞留人数</AREA_DESC>\n" +
//				"                  <AREA_NUM>AIRPORT-COUNT</AREA_NUM>\n" +
//				"                  <AREA_TYPE>9</AREA_TYPE>\n" +
//				"                  <SUB_AREA>\n" +
//				"                     <SUB_DESC>进离港人数</SUB_DESC>\n" +
//				"                     <SUB_AREA>\n" +
//				"                        <SUB_DESC>进港人数</SUB_DESC>\n" +
//				"                        <SUB_NUM>AIRPORT-COUNT-ARR</SUB_NUM>\n" +
//				"                        <SUB_TYPE>9</SUB_TYPE>\n" +
//				"                     </SUB_AREA>\n" +
//				"                     <SUB_AREA>\n" +
//				"                        <SUB_DESC>离港人数</SUB_DESC>\n" +
//				"                        <SUB_NUM>AIRPORT-COUNT-DEP</SUB_NUM>\n" +
//				"                        <SUB_TYPE>9</SUB_TYPE>\n" +
//				"                     </SUB_AREA>\n" +
//				"                     <SUB_NUM>AIRPORT-COUNT-ARR-DEP</SUB_NUM>\n" +
//				"                     <SUB_TYPE>9</SUB_TYPE>\n" +
//				"                  </SUB_AREA>\n" +
//				"                  <SUB_AREA>\n" +
//				"                     <SUB_DESC>航站楼路测滞留人数</SUB_DESC>\n" +
//				"                     <SUB_NUM>TERMINAL-STAY</SUB_NUM>\n" +
//				"                     <SUB_TYPE>9</SUB_TYPE>\n" +
//				"                  </SUB_AREA>\n" +
//				"               </AREA>\n" +
//				"               <AREA>\n" +
//				"                  <AREA_DESC>安检区</AREA_DESC>\n" +
//				"                  <AREA_NUM>AJ</AREA_NUM>\n" +
//				"                  <AREA_TYPE>2</AREA_TYPE>\n" +
//				"                  <SUB_AREA>\n" +
//				"                     <SUB_DESC>1F安检区(国际到达)</SUB_DESC>\n" +
//				"                     <SUB_AREA>\n" +
//				"                        <SUB_DESC>1F联检L01</SUB_DESC>\n" +
//				"                        <SUB_NUM>1F-AJ-L01</SUB_NUM>\n" +
//				"                        <SUB_TYPE>2</SUB_TYPE>\n" +
//				"                     </SUB_AREA>\n" +
//				"                     <SUB_AREA>\n" +
//				"                        <SUB_DESC>1F联检L02</SUB_DESC>\n" +
//				"                        <SUB_NUM>1F-AJ-L02</SUB_NUM>\n" +
//				"                        <SUB_TYPE>2</SUB_TYPE>\n" +
//				"                     </SUB_AREA>\n" +
//				"                     <SUB_NUM>1F-AJ</SUB_NUM>\n" +
//				"                     <SUB_TYPE>2</SUB_TYPE>\n" +
//				"                  </SUB_AREA>\n" +
//				"                  <SUB_AREA>\n" +
//				"                     <SUB_DESC>2F安检区-中转</SUB_DESC>\n" +
//				"                     <SUB_AREA>\n" +
//				"                        <SUB_DESC>2F安检T01</SUB_DESC>\n" +
//				"                        <SUB_NUM>T1-TC01-YZ</SUB_NUM>\n" +
//				"                        <SUB_TYPE>2</SUB_TYPE>\n" +
//				"                     </SUB_AREA>\n" +
//				"                     <SUB_AREA>\n" +
//				"                        <SUB_DESC>2F安检T02</SUB_DESC>\n" +
//				"                        <SUB_NUM>T1-TC02-YZ</SUB_NUM>\n" +
//				"                        <SUB_TYPE>2</SUB_TYPE>\n" +
//				"                     </SUB_AREA>\n" +
//				"                     <SUB_AREA>\n" +
//				"                        <SUB_DESC>2F安检T03</SUB_DESC>\n" +
//				"                        <SUB_NUM>T1-TC03-YZ</SUB_NUM>\n" +
//				"                        <SUB_TYPE>2</SUB_TYPE>\n" +
//				"                     </SUB_AREA>\n" +
//				"                     <SUB_AREA>\n" +
//				"                        <SUB_DESC>2F安检T04</SUB_DESC>\n" +
//				"                        <SUB_NUM>T1-TC04-YZ</SUB_NUM>\n" +
//				"                        <SUB_TYPE>2</SUB_TYPE>\n" +
//				"                     </SUB_AREA>\n" +
//				"                     <SUB_AREA>\n" +
//				"                        <SUB_DESC>2F安检T08</SUB_DESC>\n" +
//				"                        <SUB_NUM>T1-TC08-YZ</SUB_NUM>\n" +
//				"                        <SUB_TYPE>2</SUB_TYPE>\n" +
//				"                     </SUB_AREA>\n" +
//				"                     <SUB_NUM>2F-AJ</SUB_NUM>\n" +
//				"                     <SUB_TYPE>2</SUB_TYPE>\n" +
//				"                  </SUB_AREA>\n" +
//				"                  <SUB_AREA>\n" +
//				"                     <SUB_DESC>3F安检区(国内出发)</SUB_DESC>\n" +
//				"                     <SUB_AREA>\n" +
//				"                        <SUB_DESC>3F安检东区</SUB_DESC>\n" +
//				"                        <SUB_AREA>\n" +
//				"                           <SUB_DESC>3F安检东S形</SUB_DESC>\n" +
//				"                           <SUB_NUM>3F-AJ-DONG-SX</SUB_NUM>\n" +
//				"                           <SUB_TYPE>2</SUB_TYPE>\n" +
//				"                        </SUB_AREA>\n" +
//				"                        <SUB_AREA>\n" +
//				"                           <SUB_DESC>3F安检D23</SUB_DESC>\n" +
//				"                           <SUB_NUM>T1-DC23-ZY</SUB_NUM>\n" +
//				"                           <SUB_TYPE>2</SUB_TYPE>\n" +
//				"                        </SUB_AREA>\n" +
//				"                        <SUB_AREA>\n" +
//				"                           <SUB_DESC>3F安检D24</SUB_DESC>\n" +
//				"                           <SUB_NUM>T1-DC24-ZY</SUB_NUM>\n" +
//				"                           <SUB_TYPE>2</SUB_TYPE>\n" +
//				"                        </SUB_AREA>\n" +
//				"                        <SUB_AREA>\n" +
//				"                           <SUB_DESC>3F安检D25人工</SUB_DESC>\n" +
//				"                           <SUB_NUM>T1-DC25-YZ</SUB_NUM>\n" +
//				"                           <SUB_TYPE>2</SUB_TYPE>\n" +
//				"                        </SUB_AREA>\n" +
//				"                        <SUB_AREA>\n" +
//				"                           <SUB_DESC>3F安检D25</SUB_DESC>\n" +
//				"                           <SUB_NUM>T1-DC25-ZY</SUB_NUM>\n" +
//				"                           <SUB_TYPE>2</SUB_TYPE>\n" +
//				"                        </SUB_AREA>\n" +
//				"                        <SUB_AREA>\n" +
//				"                           <SUB_DESC>3F安检D26</SUB_DESC>\n" +
//				"                           <SUB_NUM>T1-DC26-ZY</SUB_NUM>\n" +
//				"                           <SUB_TYPE>2</SUB_TYPE>\n" +
//				"                        </SUB_AREA>\n" +
//				"                        <SUB_AREA>\n" +
//				"                           <SUB_DESC>3F安检D27人工</SUB_DESC>\n" +
//				"                           <SUB_NUM>T1-DC27-YZ</SUB_NUM>\n" +
//				"                           <SUB_TYPE>2</SUB_TYPE>\n" +
//				"                        </SUB_AREA>\n" +
//				"                        <SUB_AREA>\n" +
//				"                           <SUB_DESC>3F安检D27</SUB_DESC>\n" +
//				"                           <SUB_NUM>T1-DC27-ZY</SUB_NUM>\n" +
//				"                           <SUB_TYPE>2</SUB_TYPE>\n" +
//				"                        </SUB_AREA>\n" +
//				"                        <SUB_AREA>\n" +
//				"                           <SUB_DESC>3F安检D28</SUB_DESC>\n" +
//				"                           <SUB_NUM>T1-DC28-ZY</SUB_NUM>\n" +
//				"                           <SUB_TYPE>2</SUB_TYPE>\n" +
//				"                        </SUB_AREA>\n" +
//				"                        <SUB_AREA>\n" +
//				"                           <SUB_DESC>3F安检D29人工</SUB_DESC>\n" +
//				"                           <SUB_NUM>T1-DC29-YZ</SUB_NUM>\n" +
//				"                           <SUB_TYPE>2</SUB_TYPE>\n" +
//				"                        </SUB_AREA>\n" +
//				"                        <SUB_AREA>\n" +
//				"                           <SUB_DESC>3F安检D29</SUB_DESC>\n" +
//				"                           <SUB_NUM>T1-DC29-ZY</SUB_NUM>\n" +
//				"                           <SUB_TYPE>2</SUB_TYPE>\n" +
//				"                        </SUB_AREA>\n" +
//				"                        <SUB_AREA>\n" +
//				"                           <SUB_DESC>3F安检D30</SUB_DESC>\n" +
//				"                           <SUB_NUM>T1-DC30-ZY</SUB_NUM>\n" +
//				"                           <SUB_TYPE>2</SUB_TYPE>\n" +
//				"                        </SUB_AREA>\n" +
//				"                        <SUB_AREA>\n" +
//				"                           <SUB_DESC>3F安检D31人工</SUB_DESC>\n" +
//				"                           <SUB_NUM>T1-DC31-YZ</SUB_NUM>\n" +
//				"                           <SUB_TYPE>2</SUB_TYPE>\n" +
//				"                        </SUB_AREA>\n" +
//				"                        <SUB_AREA>\n" +
//				"                           <SUB_DESC>3F安检D31</SUB_DESC>\n" +
//				"                           <SUB_NUM>T1-DC31-ZY</SUB_NUM>\n" +
//				"                           <SUB_TYPE>2</SUB_TYPE>\n" +
//				"                        </SUB_AREA>\n" +
//				"                        <SUB_AREA>\n" +
//				"                           <SUB_DESC>3F安检D32</SUB_DESC>\n" +
//				"                           <SUB_NUM>T1-DC32-ZY</SUB_NUM>\n" +
//				"                           <SUB_TYPE>2</SUB_TYPE>\n" +
//				"                        </SUB_AREA>\n" +
//				"                        <SUB_AREA>\n" +
//				"                           <SUB_DESC>3F安检D33人工</SUB_DESC>\n" +
//				"                           <SUB_NUM>T1-DC33-YZ</SUB_NUM>\n" +
//				"                           <SUB_TYPE>2</SUB_TYPE>\n" +
//				"                        </SUB_AREA>\n" +
//				"                        <SUB_NUM>3F-AJ-DONG</SUB_NUM>\n" +
//				"                        <SUB_TYPE>2</SUB_TYPE>\n" +
//				"                     </SUB_AREA>\n" +
//				"                     <SUB_AREA>\n" +
//				"                        <SUB_DESC>3F安检西区</SUB_DESC>\n" +
//				"                        <SUB_AREA>\n" +
//				"                           <SUB_DESC>3F安检西S形</SUB_DESC>\n" +
//				"                           <SUB_NUM>3F-AJ-XI-SX</SUB_NUM>\n" +
//				"                           <SUB_TYPE>2</SUB_TYPE>\n" +
//				"                        </SUB_AREA>\n" +
//				"                        <SUB_AREA>\n" +
//				"                           <SUB_DESC>3F安检D13人工</SUB_DESC>\n" +
//				"                           <SUB_NUM>T1-DC13-YZ</SUB_NUM>\n" +
//				"                           <SUB_TYPE>2</SUB_TYPE>\n" +
//				"                        </SUB_AREA>\n" +
//				"                        <SUB_AREA>\n" +
//				"                           <SUB_DESC>3F安检D13</SUB_DESC>\n" +
//				"                           <SUB_NUM>T1-DC13-ZY</SUB_NUM>\n" +
//				"                           <SUB_TYPE>2</SUB_TYPE>\n" +
//				"                        </SUB_AREA>\n" +
//				"                        <SUB_AREA>\n" +
//				"                           <SUB_DESC>3F安检D14</SUB_DESC>\n" +
//				"                           <SUB_NUM>T1-DC14-ZY</SUB_NUM>\n" +
//				"                           <SUB_TYPE>2</SUB_TYPE>\n" +
//				"                        </SUB_AREA>\n" +
//				"                        <SUB_AREA>\n" +
//				"                           <SUB_DESC>3F安检D15人工</SUB_DESC>\n" +
//				"                           <SUB_NUM>T1-DC15-YZ</SUB_NUM>\n" +
//				"                           <SUB_TYPE>2</SUB_TYPE>\n" +
//				"                        </SUB_AREA>\n" +
//				"                        <SUB_AREA>\n" +
//				"                           <SUB_DESC>3F安检D15</SUB_DESC>\n" +
//				"                           <SUB_NUM>T1-DC15-ZY</SUB_NUM>\n" +
//				"                           <SUB_TYPE>2</SUB_TYPE>\n" +
//				"                        </SUB_AREA>\n" +
//				"                        <SUB_AREA>\n" +
//				"                           <SUB_DESC>3F安检D16</SUB_DESC>\n" +
//				"                           <SUB_NUM>T1-DC16-ZY</SUB_NUM>\n" +
//				"                           <SUB_TYPE>2</SUB_TYPE>\n" +
//				"                        </SUB_AREA>\n" +
//				"                        <SUB_AREA>\n" +
//				"                           <SUB_DESC>3F安检D17人工</SUB_DESC>\n" +
//				"                           <SUB_NUM>T1-DC17-YZ</SUB_NUM>\n" +
//				"                           <SUB_TYPE>2</SUB_TYPE>\n" +
//				"                        </SUB_AREA>\n" +
//				"                        <SUB_AREA>\n" +
//				"                           <SUB_DESC>3F安检D17</SUB_DESC>\n" +
//				"                           <SUB_NUM>T1-DC17-ZY</SUB_NUM>\n" +
//				"                           <SUB_TYPE>2</SUB_TYPE>\n" +
//				"                        </SUB_AREA>\n" +
//				"                        <SUB_AREA>\n" +
//				"                           <SUB_DESC>3F安检D18</SUB_DESC>\n" +
//				"                           <SUB_NUM>T1-DC18-ZY</SUB_NUM>\n" +
//				"                           <SUB_TYPE>2</SUB_TYPE>\n" +
//				"                        </SUB_AREA>\n" +
//				"                        <SUB_AREA>\n" +
//				"                           <SUB_DESC>3F安检D19人工</SUB_DESC>\n" +
//				"                           <SUB_NUM>T1-DC19-YZ</SUB_NUM>\n" +
//				"                           <SUB_TYPE>2</SUB_TYPE>\n" +
//				"                        </SUB_AREA>\n" +
//				"                        <SUB_AREA>\n" +
//				"                           <SUB_DESC>3F安检D19</SUB_DESC>\n" +
//				"                           <SUB_NUM>T1-DC19-ZY</SUB_NUM>\n" +
//				"                           <SUB_TYPE>2</SUB_TYPE>\n" +
//				"                        </SUB_AREA>\n" +
//				"                        <SUB_AREA>\n" +
//				"                           <SUB_DESC>3F安检D20</SUB_DESC>\n" +
//				"                           <SUB_NUM>T1-DC20-ZY</SUB_NUM>\n" +
//				"                           <SUB_TYPE>2</SUB_TYPE>\n" +
//				"                        </SUB_AREA>\n" +
//				"                        <SUB_AREA>\n" +
//				"                           <SUB_DESC>3F安检D21人工</SUB_DESC>\n" +
//				"                           <SUB_NUM>T1-DC21-YZ</SUB_NUM>\n" +
//				"                           <SUB_TYPE>2</SUB_TYPE>\n" +
//				"                        </SUB_AREA>\n" +
//				"                        <SUB_AREA>\n" +
//				"                           <SUB_DESC>3F安检D21</SUB_DESC>\n" +
//				"                           <SUB_NUM>T1-DC21-ZY</SUB_NUM>\n" +
//				"                           <SUB_TYPE>2</SUB_TYPE>\n" +
//				"                        </SUB_AREA>\n" +
//				"                        <SUB_AREA>\n" +
//				"                           <SUB_DESC>3F安检D22</SUB_DESC>\n" +
//				"                           <SUB_NUM>T1-DC22-ZY</SUB_NUM>\n" +
//				"                           <SUB_TYPE>2</SUB_TYPE>\n" +
//				"                        </SUB_AREA>\n" +
//				"                        <SUB_NUM>3F-AJ-XI</SUB_NUM>\n" +
//				"                        <SUB_TYPE>2</SUB_TYPE>\n" +
//				"                     </SUB_AREA>\n" +
//				"                     <SUB_NUM>3F-AJ</SUB_NUM>\n" +
//				"                     <SUB_TYPE>2</SUB_TYPE>\n" +
//				"                  </SUB_AREA>\n" +
//				"                  <SUB_AREA>\n" +
//				"                     <SUB_DESC>4F安检(国际出发)</SUB_DESC>\n" +
//				"                     <SUB_AREA>\n" +
//				"                        <SUB_DESC>4F安检S形</SUB_DESC>\n" +
//				"                        <SUB_NUM>4F-AJ-SX</SUB_NUM>\n" +
//				"                        <SUB_TYPE>2</SUB_TYPE>\n" +
//				"                     </SUB_AREA>\n" +
//				"                     <SUB_AREA>\n" +
//				"                        <SUB_DESC>4F安检I04</SUB_DESC>\n" +
//				"                        <SUB_NUM>T1-IC04-YZ</SUB_NUM>\n" +
//				"                        <SUB_TYPE>2</SUB_TYPE>\n" +
//				"                     </SUB_AREA>\n" +
//				"                     <SUB_AREA>\n" +
//				"                        <SUB_DESC>4F安检I06</SUB_DESC>\n" +
//				"                        <SUB_NUM>T1-IC06-YZ</SUB_NUM>\n" +
//				"                        <SUB_TYPE>2</SUB_TYPE>\n" +
//				"                     </SUB_AREA>\n" +
//				"                     <SUB_AREA>\n" +
//				"                        <SUB_DESC>4F安检I07</SUB_DESC>\n" +
//				"                        <SUB_NUM>T1-IC07-YZ</SUB_NUM>\n" +
//				"                        <SUB_TYPE>2</SUB_TYPE>\n" +
//				"                     </SUB_AREA>\n" +
//				"                     <SUB_AREA>\n" +
//				"                        <SUB_DESC>4F安检I08</SUB_DESC>\n" +
//				"                        <SUB_NUM>T1-IC08-YZ</SUB_NUM>\n" +
//				"                        <SUB_TYPE>2</SUB_TYPE>\n" +
//				"                     </SUB_AREA>\n" +
//				"                     <SUB_AREA>\n" +
//				"                        <SUB_DESC>4F安检I09</SUB_DESC>\n" +
//				"                        <SUB_NUM>T1-IC09-YZ</SUB_NUM>\n" +
//				"                        <SUB_TYPE>2</SUB_TYPE>\n" +
//				"                     </SUB_AREA>\n" +
//				"                     <SUB_AREA>\n" +
//				"                        <SUB_DESC>4F安检I10</SUB_DESC>\n" +
//				"                        <SUB_NUM>T1-IC10-YZ</SUB_NUM>\n" +
//				"                        <SUB_TYPE>2</SUB_TYPE>\n" +
//				"                     </SUB_AREA>\n" +
//				"                     <SUB_AREA>\n" +
//				"                        <SUB_DESC>4F安检I11</SUB_DESC>\n" +
//				"                        <SUB_NUM>T1-IC11-YZ</SUB_NUM>\n" +
//				"                        <SUB_TYPE>2</SUB_TYPE>\n" +
//				"                     </SUB_AREA>\n" +
//				"                     <SUB_AREA>\n" +
//				"                        <SUB_DESC>4F安检I12</SUB_DESC>\n" +
//				"                        <SUB_NUM>T1-IC12-YZ</SUB_NUM>\n" +
//				"                        <SUB_TYPE>2</SUB_TYPE>\n" +
//				"                     </SUB_AREA>\n" +
//				"                     <SUB_AREA>\n" +
//				"                        <SUB_DESC>4F安检I13</SUB_DESC>\n" +
//				"                        <SUB_NUM>T1-IC13-YZ</SUB_NUM>\n" +
//				"                        <SUB_TYPE>2</SUB_TYPE>\n" +
//				"                     </SUB_AREA>\n" +
//				"                     <SUB_AREA>\n" +
//				"                        <SUB_DESC>4F安检I14</SUB_DESC>\n" +
//				"                        <SUB_NUM>T1-IC14-YZ</SUB_NUM>\n" +
//				"                        <SUB_TYPE>2</SUB_TYPE>\n" +
//				"                     </SUB_AREA>\n" +
//				"                     <SUB_AREA>\n" +
//				"                        <SUB_DESC>4F安检I15</SUB_DESC>\n" +
//				"                        <SUB_NUM>T1-IC15-YZ</SUB_NUM>\n" +
//				"                        <SUB_TYPE>2</SUB_TYPE>\n" +
//				"                     </SUB_AREA>\n" +
//				"                     <SUB_AREA>\n" +
//				"                        <SUB_DESC>4F安检I16</SUB_DESC>\n" +
//				"                        <SUB_NUM>T1-IC16-YZ</SUB_NUM>\n" +
//				"                        <SUB_TYPE>2</SUB_TYPE>\n" +
//				"                     </SUB_AREA>\n" +
//				"                     <SUB_NUM>4F-AJ</SUB_NUM>\n" +
//				"                     <SUB_TYPE>2</SUB_TYPE>\n" +
//				"                  </SUB_AREA>\n" +
//				"                  <SUB_AREA>\n" +
//				"                     <SUB_DESC>B1安检区(国内出发 )</SUB_DESC>\n" +
//				"                     <SUB_AREA>\n" +
//				"                        <SUB_DESC>B1安检S形</SUB_DESC>\n" +
//				"                        <SUB_NUM>B1-AJ-SX</SUB_NUM>\n" +
//				"                        <SUB_TYPE>2</SUB_TYPE>\n" +
//				"                     </SUB_AREA>\n" +
//				"                     <SUB_AREA>\n" +
//				"                        <SUB_DESC>B1安检D63</SUB_DESC>\n" +
//				"                        <SUB_NUM>T1-DC63-ZY</SUB_NUM>\n" +
//				"                        <SUB_TYPE>2</SUB_TYPE>\n" +
//				"                     </SUB_AREA>\n" +
//				"                     <SUB_AREA>\n" +
//				"                        <SUB_DESC>B1安检D64</SUB_DESC>\n" +
//				"                        <SUB_NUM>T1-DC64-ZY</SUB_NUM>\n" +
//				"                        <SUB_TYPE>2</SUB_TYPE>\n" +
//				"                     </SUB_AREA>\n" +
//				"                     <SUB_AREA>\n" +
//				"                        <SUB_DESC>B1安检D65人工</SUB_DESC>\n" +
//				"                        <SUB_NUM>T1-DC65-YZ</SUB_NUM>\n" +
//				"                        <SUB_TYPE>2</SUB_TYPE>\n" +
//				"                     </SUB_AREA>\n" +
//				"                     <SUB_AREA>\n" +
//				"                        <SUB_DESC>B1安检D65</SUB_DESC>\n" +
//				"                        <SUB_NUM>T1-DC65-ZY</SUB_NUM>\n" +
//				"                        <SUB_TYPE>2</SUB_TYPE>\n" +
//				"                     </SUB_AREA>\n" +
//				"                     <SUB_AREA>\n" +
//				"                        <SUB_DESC>B1安检D66</SUB_DESC>\n" +
//				"                        <SUB_NUM>T1-DC66-ZY</SUB_NUM>\n" +
//				"                        <SUB_TYPE>2</SUB_TYPE>\n" +
//				"                     </SUB_AREA>\n" +
//				"                     <SUB_AREA>\n" +
//				"                        <SUB_DESC>B1安检D67</SUB_DESC>\n" +
//				"                        <SUB_NUM>T1-DC67-ZY</SUB_NUM>\n" +
//				"                        <SUB_TYPE>2</SUB_TYPE>\n" +
//				"                     </SUB_AREA>\n" +
//				"                     <SUB_AREA>\n" +
//				"                        <SUB_DESC>B1安检D68</SUB_DESC>\n" +
//				"                        <SUB_NUM>T1-DC68-ZY</SUB_NUM>\n" +
//				"                        <SUB_TYPE>2</SUB_TYPE>\n" +
//				"                     </SUB_AREA>\n" +
//				"                     <SUB_NUM>B1-AJ</SUB_NUM>\n" +
//				"                     <SUB_TYPE>2</SUB_TYPE>\n" +
//				"                  </SUB_AREA>\n" +
//				"               </AREA>\n" +
//				"               <AREA>\n" +
//				"                  <AREA_DESC>大巴等候区</AREA_DESC>\n" +
//				"                  <AREA_NUM>BUS</AREA_NUM>\n" +
//				"                  <AREA_TYPE>5</AREA_TYPE>\n" +
//				"               </AREA>\n" +
//				"               <AREA>\n" +
//				"                  <AREA_DESC>主要出入口</AREA_DESC>\n" +
//				"                  <AREA_NUM>CR</AREA_NUM>\n" +
//				"                  <AREA_TYPE>7</AREA_TYPE>\n" +
//				"                  <SUB_AREA>\n" +
//				"                     <SUB_DESC>1F主要出入口</SUB_DESC>\n" +
//				"                     <SUB_AREA>\n" +
//				"                        <SUB_DESC>1F-18号门</SUB_DESC>\n" +
//				"                        <SUB_NUM>1F-CR-18</SUB_NUM>\n" +
//				"                        <SUB_TYPE>7</SUB_TYPE>\n" +
//				"                     </SUB_AREA>\n" +
//				"                     <SUB_AREA>\n" +
//				"                        <SUB_DESC>1F-19号门</SUB_DESC>\n" +
//				"                        <SUB_NUM>1F-CR-19</SUB_NUM>\n" +
//				"                        <SUB_TYPE>7</SUB_TYPE>\n" +
//				"                     </SUB_AREA>\n" +
//				"                     <SUB_AREA>\n" +
//				"                        <SUB_DESC>1F-20号门</SUB_DESC>\n" +
//				"                        <SUB_NUM>1F-CR-20</SUB_NUM>\n" +
//				"                        <SUB_TYPE>7</SUB_TYPE>\n" +
//				"                     </SUB_AREA>\n" +
//				"                     <SUB_NUM>1F-CR</SUB_NUM>\n" +
//				"                     <SUB_TYPE>7</SUB_TYPE>\n" +
//				"                  </SUB_AREA>\n" +
//				"                  <SUB_AREA>\n" +
//				"                     <SUB_DESC>2F主要出入口</SUB_DESC>\n" +
//				"                     <SUB_AREA>\n" +
//				"                        <SUB_DESC>2F-13号门</SUB_DESC>\n" +
//				"                        <SUB_NUM>2F-CR-13</SUB_NUM>\n" +
//				"                        <SUB_TYPE>7</SUB_TYPE>\n" +
//				"                     </SUB_AREA>\n" +
//				"                     <SUB_AREA>\n" +
//				"                        <SUB_DESC>2F-14号门</SUB_DESC>\n" +
//				"                        <SUB_NUM>2F-CR-14</SUB_NUM>\n" +
//				"                        <SUB_TYPE>7</SUB_TYPE>\n" +
//				"                     </SUB_AREA>\n" +
//				"                     <SUB_NUM>2F-CR</SUB_NUM>\n" +
//				"                     <SUB_TYPE>7</SUB_TYPE>\n" +
//				"                  </SUB_AREA>\n" +
//				"                  <SUB_AREA>\n" +
//				"                     <SUB_DESC>3F主要出入口</SUB_DESC>\n" +
//				"                     <SUB_AREA>\n" +
//				"                        <SUB_DESC>3F-10号门</SUB_DESC>\n" +
//				"                        <SUB_NUM>3F-CR-10</SUB_NUM>\n" +
//				"                        <SUB_TYPE>7</SUB_TYPE>\n" +
//				"                     </SUB_AREA>\n" +
//				"                     <SUB_AREA>\n" +
//				"                        <SUB_DESC>3F-11号门</SUB_DESC>\n" +
//				"                        <SUB_NUM>3F-CR-11</SUB_NUM>\n" +
//				"                        <SUB_TYPE>7</SUB_TYPE>\n" +
//				"                     </SUB_AREA>\n" +
//				"                     <SUB_AREA>\n" +
//				"                        <SUB_DESC>3F-12号门</SUB_DESC>\n" +
//				"                        <SUB_NUM>3F-CR-12</SUB_NUM>\n" +
//				"                        <SUB_TYPE>7</SUB_TYPE>\n" +
//				"                     </SUB_AREA>\n" +
//				"                     <SUB_AREA>\n" +
//				"                        <SUB_DESC>3F-7号门</SUB_DESC>\n" +
//				"                        <SUB_NUM>3F-CR-7</SUB_NUM>\n" +
//				"                        <SUB_TYPE>7</SUB_TYPE>\n" +
//				"                     </SUB_AREA>\n" +
//				"                     <SUB_AREA>\n" +
//				"                        <SUB_DESC>3F-8号门</SUB_DESC>\n" +
//				"                        <SUB_NUM>3F-CR-8</SUB_NUM>\n" +
//				"                        <SUB_TYPE>7</SUB_TYPE>\n" +
//				"                     </SUB_AREA>\n" +
//				"                     <SUB_AREA>\n" +
//				"                        <SUB_DESC>3F-9号门</SUB_DESC>\n" +
//				"                        <SUB_NUM>3F-CR-9</SUB_NUM>\n" +
//				"                        <SUB_TYPE>7</SUB_TYPE>\n" +
//				"                     </SUB_AREA>\n" +
//				"                     <SUB_NUM>3F-CR</SUB_NUM>\n" +
//				"                     <SUB_TYPE>7</SUB_TYPE>\n" +
//				"                  </SUB_AREA>\n" +
//				"                  <SUB_AREA>\n" +
//				"                     <SUB_DESC>4F主要出入口</SUB_DESC>\n" +
//				"                     <SUB_AREA>\n" +
//				"                        <SUB_DESC>4F-1号门</SUB_DESC>\n" +
//				"                        <SUB_NUM>4F-CR-1</SUB_NUM>\n" +
//				"                        <SUB_TYPE>7</SUB_TYPE>\n" +
//				"                     </SUB_AREA>\n" +
//				"                     <SUB_AREA>\n" +
//				"                        <SUB_DESC>4F-2号门</SUB_DESC>\n" +
//				"                        <SUB_NUM>4F-CR-2</SUB_NUM>\n" +
//				"                        <SUB_TYPE>7</SUB_TYPE>\n" +
//				"                     </SUB_AREA>\n" +
//				"                     <SUB_AREA>\n" +
//				"                        <SUB_DESC>4F-3号门</SUB_DESC>\n" +
//				"                        <SUB_NUM>4F-CR-3</SUB_NUM>\n" +
//				"                        <SUB_TYPE>7</SUB_TYPE>\n" +
//				"                     </SUB_AREA>\n" +
//				"                     <SUB_AREA>\n" +
//				"                        <SUB_DESC>4F-4号门</SUB_DESC>\n" +
//				"                        <SUB_NUM>4F-CR-4</SUB_NUM>\n" +
//				"                        <SUB_TYPE>7</SUB_TYPE>\n" +
//				"                     </SUB_AREA>\n" +
//				"                     <SUB_AREA>\n" +
//				"                        <SUB_DESC>4F-5号门</SUB_DESC>\n" +
//				"                        <SUB_NUM>4F-CR-5</SUB_NUM>\n" +
//				"                        <SUB_TYPE>7</SUB_TYPE>\n" +
//				"                     </SUB_AREA>\n" +
//				"                     <SUB_AREA>\n" +
//				"                        <SUB_DESC>4F-6号门</SUB_DESC>\n" +
//				"                        <SUB_NUM>4F-CR-6</SUB_NUM>\n" +
//				"                        <SUB_TYPE>7</SUB_TYPE>\n" +
//				"                     </SUB_AREA>\n" +
//				"                     <SUB_NUM>4F-CR</SUB_NUM>\n" +
//				"                     <SUB_TYPE>7</SUB_TYPE>\n" +
//				"                  </SUB_AREA>\n" +
//				"                  <SUB_AREA>\n" +
//				"                     <SUB_DESC>B1-28号门</SUB_DESC>\n" +
//				"                     <SUB_NUM>B1-CR-28</SUB_NUM>\n" +
//				"                     <SUB_TYPE>7</SUB_TYPE>\n" +
//				"                  </SUB_AREA>\n" +
//				"               </AREA>\n" +
//				"               <AREA>\n" +
//				"                  <AREA_DESC>直梯区</AREA_DESC>\n" +
//				"                  <AREA_NUM>LADDER</AREA_NUM>\n" +
//				"                  <AREA_TYPE>8</AREA_TYPE>\n" +
//				"                  <SUB_AREA>\n" +
//				"                     <SUB_DESC>直梯1F</SUB_DESC>\n" +
//				"                     <SUB_AREA>\n" +
//				"                        <SUB_DESC>直梯1F-02</SUB_DESC>\n" +
//				"                        <SUB_NUM>ZT-1F-02</SUB_NUM>\n" +
//				"                        <SUB_TYPE>8</SUB_TYPE>\n" +
//				"                     </SUB_AREA>\n" +
//				"                     <SUB_AREA>\n" +
//				"                        <SUB_DESC>直梯1F-03</SUB_DESC>\n" +
//				"                        <SUB_NUM>ZT-1F-03</SUB_NUM>\n" +
//				"                        <SUB_TYPE>8</SUB_TYPE>\n" +
//				"                     </SUB_AREA>\n" +
//				"                     <SUB_AREA>\n" +
//				"                        <SUB_DESC>直梯1F-04</SUB_DESC>\n" +
//				"                        <SUB_NUM>ZT-1F-04</SUB_NUM>\n" +
//				"                        <SUB_TYPE>8</SUB_TYPE>\n" +
//				"                     </SUB_AREA>\n" +
//				"                     <SUB_AREA>\n" +
//				"                        <SUB_DESC>直梯1F-12</SUB_DESC>\n" +
//				"                        <SUB_NUM>ZT-1F-12</SUB_NUM>\n" +
//				"                        <SUB_TYPE>8</SUB_TYPE>\n" +
//				"                     </SUB_AREA>\n" +
//				"                     <SUB_AREA>\n" +
//				"                        <SUB_DESC>直梯1F-13</SUB_DESC>\n" +
//				"                        <SUB_NUM>ZT-1F-13</SUB_NUM>\n" +
//				"                        <SUB_TYPE>8</SUB_TYPE>\n" +
//				"                     </SUB_AREA>\n" +
//				"                     <SUB_AREA>\n" +
//				"                        <SUB_DESC>直梯1F-D3</SUB_DESC>\n" +
//				"                        <SUB_NUM>ZT-1F-D3</SUB_NUM>\n" +
//				"                        <SUB_TYPE>8</SUB_TYPE>\n" +
//				"                     </SUB_AREA>\n" +
//				"                     <SUB_NUM>ZT-1F</SUB_NUM>\n" +
//				"                     <SUB_TYPE>8</SUB_TYPE>\n" +
//				"                  </SUB_AREA>\n" +
//				"                  <SUB_AREA>\n" +
//				"                     <SUB_DESC>直梯2F</SUB_DESC>\n" +
//				"                     <SUB_AREA>\n" +
//				"                        <SUB_DESC>直梯2F-02</SUB_DESC>\n" +
//				"                        <SUB_NUM>ZT-2F-02</SUB_NUM>\n" +
//				"                        <SUB_TYPE>8</SUB_TYPE>\n" +
//				"                     </SUB_AREA>\n" +
//				"                     <SUB_AREA>\n" +
//				"                        <SUB_DESC>直梯2F-03</SUB_DESC>\n" +
//				"                        <SUB_NUM>ZT-2F-03</SUB_NUM>\n" +
//				"                        <SUB_TYPE>8</SUB_TYPE>\n" +
//				"                     </SUB_AREA>\n" +
//				"                     <SUB_AREA>\n" +
//				"                        <SUB_DESC>直梯2F-04</SUB_DESC>\n" +
//				"                        <SUB_NUM>ZT-2F-04</SUB_NUM>\n" +
//				"                        <SUB_TYPE>8</SUB_TYPE>\n" +
//				"                     </SUB_AREA>\n" +
//				"                     <SUB_AREA>\n" +
//				"                        <SUB_DESC>直梯2F-05</SUB_DESC>\n" +
//				"                        <SUB_NUM>ZT-2F-05</SUB_NUM>\n" +
//				"                        <SUB_TYPE>8</SUB_TYPE>\n" +
//				"                     </SUB_AREA>\n" +
//				"                     <SUB_AREA>\n" +
//				"                        <SUB_DESC>直梯2F-06</SUB_DESC>\n" +
//				"                        <SUB_NUM>ZT-2F-06</SUB_NUM>\n" +
//				"                        <SUB_TYPE>8</SUB_TYPE>\n" +
//				"                     </SUB_AREA>\n" +
//				"                     <SUB_AREA>\n" +
//				"                        <SUB_DESC>直梯2F-07</SUB_DESC>\n" +
//				"                        <SUB_NUM>ZT-2F-07</SUB_NUM>\n" +
//				"                        <SUB_TYPE>8</SUB_TYPE>\n" +
//				"                     </SUB_AREA>\n" +
//				"                     <SUB_AREA>\n" +
//				"                        <SUB_DESC>直梯2F-08</SUB_DESC>\n" +
//				"                        <SUB_NUM>ZT-2F-08</SUB_NUM>\n" +
//				"                        <SUB_TYPE>8</SUB_TYPE>\n" +
//				"                     </SUB_AREA>\n" +
//				"                     <SUB_AREA>\n" +
//				"                        <SUB_DESC>直梯2F-11</SUB_DESC>\n" +
//				"                        <SUB_NUM>ZT-2F-11</SUB_NUM>\n" +
//				"                        <SUB_TYPE>8</SUB_TYPE>\n" +
//				"                     </SUB_AREA>\n" +
//				"                     <SUB_AREA>\n" +
//				"                        <SUB_DESC>直梯2F-12</SUB_DESC>\n" +
//				"                        <SUB_NUM>ZT-2F-12</SUB_NUM>\n" +
//				"                        <SUB_TYPE>8</SUB_TYPE>\n" +
//				"                     </SUB_AREA>\n" +
//				"                     <SUB_AREA>\n" +
//				"                        <SUB_DESC>直梯2F-13</SUB_DESC>\n" +
//				"                        <SUB_NUM>ZT-2F-13</SUB_NUM>\n" +
//				"                        <SUB_TYPE>8</SUB_TYPE>\n" +
//				"                     </SUB_AREA>\n" +
//				"                     <SUB_NUM>ZT-2F</SUB_NUM>\n" +
//				"                     <SUB_TYPE>8</SUB_TYPE>\n" +
//				"                  </SUB_AREA>\n" +
//				"                  <SUB_AREA>\n" +
//				"                     <SUB_DESC>直梯3F</SUB_DESC>\n" +
//				"                     <SUB_AREA>\n" +
//				"                        <SUB_DESC>直梯3F-06</SUB_DESC>\n" +
//				"                        <SUB_NUM>ZT-3F-</SUB_NUM>\n" +
//				"                        <SUB_TYPE>8</SUB_TYPE>\n" +
//				"                     </SUB_AREA>\n" +
//				"                     <SUB_AREA>\n" +
//				"                        <SUB_DESC>直梯3F-02</SUB_DESC>\n" +
//				"                        <SUB_NUM>ZT-3F-02</SUB_NUM>\n" +
//				"                        <SUB_TYPE>8</SUB_TYPE>\n" +
//				"                     </SUB_AREA>\n" +
//				"                     <SUB_AREA>\n" +
//				"                        <SUB_DESC>直梯3F-03</SUB_DESC>\n" +
//				"                        <SUB_NUM>ZT-3F-03</SUB_NUM>\n" +
//				"                        <SUB_TYPE>8</SUB_TYPE>\n" +
//				"                     </SUB_AREA>\n" +
//				"                     <SUB_AREA>\n" +
//				"                        <SUB_DESC>直梯3F-04</SUB_DESC>\n" +
//				"                        <SUB_NUM>ZT-3F-04</SUB_NUM>\n" +
//				"                        <SUB_TYPE>8</SUB_TYPE>\n" +
//				"                     </SUB_AREA>\n" +
//				"                     <SUB_AREA>\n" +
//				"                        <SUB_DESC>直梯3F-05</SUB_DESC>\n" +
//				"                        <SUB_NUM>ZT-3F-05</SUB_NUM>\n" +
//				"                        <SUB_TYPE>8</SUB_TYPE>\n" +
//				"                     </SUB_AREA>\n" +
//				"                     <SUB_AREA>\n" +
//				"                        <SUB_DESC>直梯3F-07</SUB_DESC>\n" +
//				"                        <SUB_NUM>ZT-3F-07</SUB_NUM>\n" +
//				"                        <SUB_TYPE>8</SUB_TYPE>\n" +
//				"                     </SUB_AREA>\n" +
//				"                     <SUB_AREA>\n" +
//				"                        <SUB_DESC>直梯3F-08</SUB_DESC>\n" +
//				"                        <SUB_NUM>ZT-3F-08</SUB_NUM>\n" +
//				"                        <SUB_TYPE>8</SUB_TYPE>\n" +
//				"                     </SUB_AREA>\n" +
//				"                     <SUB_AREA>\n" +
//				"                        <SUB_DESC>直梯3F-11</SUB_DESC>\n" +
//				"                        <SUB_NUM>ZT-3F-11</SUB_NUM>\n" +
//				"                        <SUB_TYPE>8</SUB_TYPE>\n" +
//				"                     </SUB_AREA>\n" +
//				"                     <SUB_AREA>\n" +
//				"                        <SUB_DESC>直梯3F-12</SUB_DESC>\n" +
//				"                        <SUB_NUM>ZT-3F-12</SUB_NUM>\n" +
//				"                        <SUB_TYPE>8</SUB_TYPE>\n" +
//				"                     </SUB_AREA>\n" +
//				"                     <SUB_AREA>\n" +
//				"                        <SUB_DESC>直梯3F-13</SUB_DESC>\n" +
//				"                        <SUB_NUM>ZT-3F-13</SUB_NUM>\n" +
//				"                        <SUB_TYPE>8</SUB_TYPE>\n" +
//				"                     </SUB_AREA>\n" +
//				"                     <SUB_NUM>ZT-3F</SUB_NUM>\n" +
//				"                     <SUB_TYPE>8</SUB_TYPE>\n" +
//				"                  </SUB_AREA>\n" +
//				"                  <SUB_AREA>\n" +
//				"                     <SUB_DESC>直梯B1F</SUB_DESC>\n" +
//				"                     <SUB_AREA>\n" +
//				"                        <SUB_DESC>直梯B1F-03</SUB_DESC>\n" +
//				"                        <SUB_NUM>ZT-B1F-03</SUB_NUM>\n" +
//				"                        <SUB_TYPE>8</SUB_TYPE>\n" +
//				"                     </SUB_AREA>\n" +
//				"                     <SUB_AREA>\n" +
//				"                        <SUB_DESC>直梯B1F-04</SUB_DESC>\n" +
//				"                        <SUB_NUM>ZT-B1F-04</SUB_NUM>\n" +
//				"                        <SUB_TYPE>8</SUB_TYPE>\n" +
//				"                     </SUB_AREA>\n" +
//				"                     <SUB_AREA>\n" +
//				"                        <SUB_DESC>直梯B1F-05</SUB_DESC>\n" +
//				"                        <SUB_NUM>ZT-B1F-05</SUB_NUM>\n" +
//				"                        <SUB_TYPE>8</SUB_TYPE>\n" +
//				"                     </SUB_AREA>\n" +
//				"                     <SUB_AREA>\n" +
//				"                        <SUB_DESC>直梯B1F-06</SUB_DESC>\n" +
//				"                        <SUB_NUM>ZT-B1F-06</SUB_NUM>\n" +
//				"                        <SUB_TYPE>8</SUB_TYPE>\n" +
//				"                     </SUB_AREA>\n" +
//				"                     <SUB_AREA>\n" +
//				"                        <SUB_DESC>直梯B1F-07</SUB_DESC>\n" +
//				"                        <SUB_NUM>ZT-B1F-07</SUB_NUM>\n" +
//				"                        <SUB_TYPE>8</SUB_TYPE>\n" +
//				"                     </SUB_AREA>\n" +
//				"                     <SUB_AREA>\n" +
//				"                        <SUB_DESC>直梯B1F-08</SUB_DESC>\n" +
//				"                        <SUB_NUM>ZT-B1F-08</SUB_NUM>\n" +
//				"                        <SUB_TYPE>8</SUB_TYPE>\n" +
//				"                     </SUB_AREA>\n" +
//				"                     <SUB_AREA>\n" +
//				"                        <SUB_DESC>直梯B1F-09</SUB_DESC>\n" +
//				"                        <SUB_NUM>ZT-B1F-09</SUB_NUM>\n" +
//				"                        <SUB_TYPE>8</SUB_TYPE>\n" +
//				"                     </SUB_AREA>\n" +
//				"                     <SUB_AREA>\n" +
//				"                        <SUB_DESC>直梯B1F-10</SUB_DESC>\n" +
//				"                        <SUB_NUM>ZT-B1F-10</SUB_NUM>\n" +
//				"                        <SUB_TYPE>8</SUB_TYPE>\n" +
//				"                     </SUB_AREA>\n" +
//				"                     <SUB_AREA>\n" +
//				"                        <SUB_DESC>直梯B1F-11</SUB_DESC>\n" +
//				"                        <SUB_NUM>ZT-B1F-11</SUB_NUM>\n" +
//				"                        <SUB_TYPE>8</SUB_TYPE>\n" +
//				"                     </SUB_AREA>\n" +
//				"                     <SUB_AREA>\n" +
//				"                        <SUB_DESC>直梯B1F-12</SUB_DESC>\n" +
//				"                        <SUB_NUM>ZT-B1F-12</SUB_NUM>\n" +
//				"                        <SUB_TYPE>8</SUB_TYPE>\n" +
//				"                     </SUB_AREA>\n" +
//				"                     <SUB_AREA>\n" +
//				"                        <SUB_DESC>直梯B1F-13</SUB_DESC>\n" +
//				"                        <SUB_NUM>ZT-B1F-13</SUB_NUM>\n" +
//				"                        <SUB_TYPE>8</SUB_TYPE>\n" +
//				"                     </SUB_AREA>\n" +
//				"                     <SUB_NUM>ZT-B1F</SUB_NUM>\n" +
//				"                     <SUB_TYPE>8</SUB_TYPE>\n" +
//				"                  </SUB_AREA>\n" +
//				"               </AREA>\n" +
//				"               <AREA>\n" +
//				"                  <AREA_DESC>行李提取区</AREA_DESC>\n" +
//				"                  <AREA_NUM>LUGGAGE</AREA_NUM>\n" +
//				"                  <AREA_TYPE>4</AREA_TYPE>\n" +
//				"                  <SUB_AREA>\n" +
//				"                     <SUB_DESC>行李提取监测</SUB_DESC>\n" +
//				"                     <SUB_NUM>LUGGAGE-TEST</SUB_NUM>\n" +
//				"                     <SUB_TYPE>4</SUB_TYPE>\n" +
//				"                  </SUB_AREA>\n" +
//				"               </AREA>\n" +
//				"               <AREA>\n" +
//				"                  <AREA_DESC>出租车等候区</AREA_DESC>\n" +
//				"                  <AREA_NUM>TAXI</AREA_NUM>\n" +
//				"                  <AREA_TYPE>6</AREA_TYPE>\n" +
//				"               </AREA>\n" +
//				"               <AREA>\n" +
//				"                  <AREA_DESC>联检区</AREA_DESC>\n" +
//				"                  <AREA_NUM>UNIONCHECK</AREA_NUM>\n" +
//				"                  <AREA_TYPE>3</AREA_TYPE>\n" +
//				"                  <SUB_AREA>\n" +
//				"                     <SUB_DESC>1F联检到达</SUB_DESC>\n" +
//				"                     <SUB_NUM>UNIONCHECK-1F</SUB_NUM>\n" +
//				"                     <SUB_TYPE>3</SUB_TYPE>\n" +
//				"                  </SUB_AREA>\n" +
//				"                  <SUB_AREA>\n" +
//				"                     <SUB_DESC>4F联检离开</SUB_DESC>\n" +
//				"                     <SUB_NUM>UNIONCHECK-4F</SUB_NUM>\n" +
//				"                     <SUB_TYPE>3</SUB_TYPE>\n" +
//				"                  </SUB_AREA>\n" +
//				"               </AREA>\n" +
//				"            </SEMS>\n" +
//				"         </return>\n" +
//				"      </ns2:getGaugeDataResponse>\n" +
//				"   </soap:Body>\n" +
//				"</soap:Envelope>";
	}

	@Override
	public String userList() {
		Map<String, Object> userMap = new LinkedHashMap<>();
		for (int i = 0; i < 10; i++) {
			User user = new User();
			user.setName("user_" + i);
			user.setSex(random() ? "男" : "女");
			user.setTall(RANDOM.nextFloat());
			user.setWeight(RANDOM.nextFloat());
			userMap.put(user.getName(), user);
		}

		return XmlUtil.makeXML("userList", userMap);
	}

	@Override
	public String self() {
		User user = new User();
		user.setName("self");
		return user.toString();
	}

	private boolean random() {
		return RANDOM.nextInt(10) % 2 == 0;
	}
}
