---
server:
  port: 8762

spring:
  profiles: peer1

eureka:
  instance:
    hostname: peer1
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://peer2:8763/eureka/
---
server:
  port: 8763
spring:
  profiles: peer2

eureka:
  instance:
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://peer1:8762/eureka/