server:
  port: 8761

spring:
  security:
    user:
      name: admin
      password: 111111

eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
  client:
#    registerWithEureka: false
    register-with-eureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/
#  server:
#    waitTimeInMsWhenSyncEmpty: 0