spring:
  application:
    name: eureka-server
---
spring:
  config:
    activate:
      on-profile: peer1

server:
  port: 7901

eureka:
  client:
    #是否将自己注册到Eureka Server,默认为true，由于当前就是server，故而设置成false，表明该服务不会向eureka注册自己的信息
    #register-with-eureka: false
    #是否从eureka server获取注册信息，由于单节点，不需要同步其他节点数据，用false
    #fetch-registry: false
    #设置服务注册中心的URL，用于client和server端交流
    service-url:
      defaultZone: http://peer2:7902/eureka
  instance:
    hostname: peer1

---
spring:
  config:
    activate:
      on-profile: peer2

server:
  port: 7902

eureka:
  client:
    #是否将自己注册到Eureka Server,默认为true，由于当前就是server，故而设置成false，表明该服务不会向eureka注册自己的信息
    #register-with-eureka: false
    #是否从eureka server获取注册信息，由于单节点，不需要同步其他节点数据，用false
    #fetch-registry: false
    #设置服务注册中心的URL，用于client和server端交流
    service-url:
      defaultZone: http://peer1:7901/eureka
  instance:
    hostname: peer2

