// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EnergyDws.proto

package com.smxknife.hbase;

public final class EnergyDws {
  private EnergyDws() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface EnergyDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:msg.EnergyData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string energyCode = 1;</code>
     */
    String getEnergyCode();
    /**
     * <code>string energyCode = 1;</code>
     */
    com.google.protobuf.ByteString
        getEnergyCodeBytes();

    /**
     * <code>string regionCode = 2;</code>
     */
    String getRegionCode();
    /**
     * <code>string regionCode = 2;</code>
     */
    com.google.protobuf.ByteString
        getRegionCodeBytes();

    /**
     * <code>string industryCode = 3;</code>
     */
    String getIndustryCode();
    /**
     * <code>string industryCode = 3;</code>
     */
    com.google.protobuf.ByteString
        getIndustryCodeBytes();

    /**
     * <code>string domainCode = 4;</code>
     */
    String getDomainCode();
    /**
     * <code>string domainCode = 4;</code>
     */
    com.google.protobuf.ByteString
        getDomainCodeBytes();

    /**
     * <code>string dataCode = 5;</code>
     */
    String getDataCode();
    /**
     * <code>string dataCode = 5;</code>
     */
    com.google.protobuf.ByteString
        getDataCodeBytes();

    /**
     * <code>double dataValue = 6;</code>
     */
    double getDataValue();

    /**
     * <code>int64 dataTime = 7;</code>
     */
    long getDataTime();
  }
  /**
   * Protobuf type {@code msg.EnergyData}
   */
  public  static final class EnergyData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:msg.EnergyData)
      EnergyDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use EnergyData.newBuilder() to construct.
    private EnergyData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EnergyData() {
      energyCode_ = "";
      regionCode_ = "";
      industryCode_ = "";
      domainCode_ = "";
      dataCode_ = "";
      dataValue_ = 0D;
      dataTime_ = 0L;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private EnergyData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              energyCode_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              regionCode_ = s;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              industryCode_ = s;
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              domainCode_ = s;
              break;
            }
            case 42: {
              String s = input.readStringRequireUtf8();

              dataCode_ = s;
              break;
            }
            case 49: {

              dataValue_ = input.readDouble();
              break;
            }
            case 56: {

              dataTime_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return EnergyDws.internal_static_msg_EnergyData_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return EnergyDws.internal_static_msg_EnergyData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              EnergyData.class, Builder.class);
    }

    public static final int ENERGYCODE_FIELD_NUMBER = 1;
    private volatile Object energyCode_;
    /**
     * <code>string energyCode = 1;</code>
     */
    public String getEnergyCode() {
      Object ref = energyCode_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        energyCode_ = s;
        return s;
      }
    }
    /**
     * <code>string energyCode = 1;</code>
     */
    public com.google.protobuf.ByteString
        getEnergyCodeBytes() {
      Object ref = energyCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        energyCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REGIONCODE_FIELD_NUMBER = 2;
    private volatile Object regionCode_;
    /**
     * <code>string regionCode = 2;</code>
     */
    public String getRegionCode() {
      Object ref = regionCode_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        regionCode_ = s;
        return s;
      }
    }
    /**
     * <code>string regionCode = 2;</code>
     */
    public com.google.protobuf.ByteString
        getRegionCodeBytes() {
      Object ref = regionCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        regionCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INDUSTRYCODE_FIELD_NUMBER = 3;
    private volatile Object industryCode_;
    /**
     * <code>string industryCode = 3;</code>
     */
    public String getIndustryCode() {
      Object ref = industryCode_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        industryCode_ = s;
        return s;
      }
    }
    /**
     * <code>string industryCode = 3;</code>
     */
    public com.google.protobuf.ByteString
        getIndustryCodeBytes() {
      Object ref = industryCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        industryCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DOMAINCODE_FIELD_NUMBER = 4;
    private volatile Object domainCode_;
    /**
     * <code>string domainCode = 4;</code>
     */
    public String getDomainCode() {
      Object ref = domainCode_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        domainCode_ = s;
        return s;
      }
    }
    /**
     * <code>string domainCode = 4;</code>
     */
    public com.google.protobuf.ByteString
        getDomainCodeBytes() {
      Object ref = domainCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        domainCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATACODE_FIELD_NUMBER = 5;
    private volatile Object dataCode_;
    /**
     * <code>string dataCode = 5;</code>
     */
    public String getDataCode() {
      Object ref = dataCode_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        dataCode_ = s;
        return s;
      }
    }
    /**
     * <code>string dataCode = 5;</code>
     */
    public com.google.protobuf.ByteString
        getDataCodeBytes() {
      Object ref = dataCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        dataCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATAVALUE_FIELD_NUMBER = 6;
    private double dataValue_;
    /**
     * <code>double dataValue = 6;</code>
     */
    public double getDataValue() {
      return dataValue_;
    }

    public static final int DATATIME_FIELD_NUMBER = 7;
    private long dataTime_;
    /**
     * <code>int64 dataTime = 7;</code>
     */
    public long getDataTime() {
      return dataTime_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getEnergyCodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, energyCode_);
      }
      if (!getRegionCodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, regionCode_);
      }
      if (!getIndustryCodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, industryCode_);
      }
      if (!getDomainCodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, domainCode_);
      }
      if (!getDataCodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, dataCode_);
      }
      if (dataValue_ != 0D) {
        output.writeDouble(6, dataValue_);
      }
      if (dataTime_ != 0L) {
        output.writeInt64(7, dataTime_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getEnergyCodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, energyCode_);
      }
      if (!getRegionCodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, regionCode_);
      }
      if (!getIndustryCodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, industryCode_);
      }
      if (!getDomainCodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, domainCode_);
      }
      if (!getDataCodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, dataCode_);
      }
      if (dataValue_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(6, dataValue_);
      }
      if (dataTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(7, dataTime_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof EnergyData)) {
        return super.equals(obj);
      }
      EnergyData other = (EnergyData) obj;

      boolean result = true;
      result = result && getEnergyCode()
          .equals(other.getEnergyCode());
      result = result && getRegionCode()
          .equals(other.getRegionCode());
      result = result && getIndustryCode()
          .equals(other.getIndustryCode());
      result = result && getDomainCode()
          .equals(other.getDomainCode());
      result = result && getDataCode()
          .equals(other.getDataCode());
      result = result && (
          Double.doubleToLongBits(getDataValue())
          == Double.doubleToLongBits(
              other.getDataValue()));
      result = result && (getDataTime()
          == other.getDataTime());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ENERGYCODE_FIELD_NUMBER;
      hash = (53 * hash) + getEnergyCode().hashCode();
      hash = (37 * hash) + REGIONCODE_FIELD_NUMBER;
      hash = (53 * hash) + getRegionCode().hashCode();
      hash = (37 * hash) + INDUSTRYCODE_FIELD_NUMBER;
      hash = (53 * hash) + getIndustryCode().hashCode();
      hash = (37 * hash) + DOMAINCODE_FIELD_NUMBER;
      hash = (53 * hash) + getDomainCode().hashCode();
      hash = (37 * hash) + DATACODE_FIELD_NUMBER;
      hash = (53 * hash) + getDataCode().hashCode();
      hash = (37 * hash) + DATAVALUE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          Double.doubleToLongBits(getDataValue()));
      hash = (37 * hash) + DATATIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getDataTime());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static EnergyData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EnergyData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EnergyData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EnergyData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EnergyData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EnergyData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EnergyData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static EnergyData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static EnergyData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static EnergyData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static EnergyData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static EnergyData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(EnergyData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code msg.EnergyData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:msg.EnergyData)
        EnergyDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return EnergyDws.internal_static_msg_EnergyData_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return EnergyDws.internal_static_msg_EnergyData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                EnergyData.class, Builder.class);
      }

      // Construct using com.smxknife.hbase.EnergyDws.EnergyData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        energyCode_ = "";

        regionCode_ = "";

        industryCode_ = "";

        domainCode_ = "";

        dataCode_ = "";

        dataValue_ = 0D;

        dataTime_ = 0L;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return EnergyDws.internal_static_msg_EnergyData_descriptor;
      }

      @Override
      public EnergyData getDefaultInstanceForType() {
        return EnergyData.getDefaultInstance();
      }

      @Override
      public EnergyData build() {
        EnergyData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public EnergyData buildPartial() {
        EnergyData result = new EnergyData(this);
        result.energyCode_ = energyCode_;
        result.regionCode_ = regionCode_;
        result.industryCode_ = industryCode_;
        result.domainCode_ = domainCode_;
        result.dataCode_ = dataCode_;
        result.dataValue_ = dataValue_;
        result.dataTime_ = dataTime_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof EnergyData) {
          return mergeFrom((EnergyData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(EnergyData other) {
        if (other == EnergyData.getDefaultInstance()) return this;
        if (!other.getEnergyCode().isEmpty()) {
          energyCode_ = other.energyCode_;
          onChanged();
        }
        if (!other.getRegionCode().isEmpty()) {
          regionCode_ = other.regionCode_;
          onChanged();
        }
        if (!other.getIndustryCode().isEmpty()) {
          industryCode_ = other.industryCode_;
          onChanged();
        }
        if (!other.getDomainCode().isEmpty()) {
          domainCode_ = other.domainCode_;
          onChanged();
        }
        if (!other.getDataCode().isEmpty()) {
          dataCode_ = other.dataCode_;
          onChanged();
        }
        if (other.getDataValue() != 0D) {
          setDataValue(other.getDataValue());
        }
        if (other.getDataTime() != 0L) {
          setDataTime(other.getDataTime());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        EnergyData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (EnergyData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object energyCode_ = "";
      /**
       * <code>string energyCode = 1;</code>
       */
      public String getEnergyCode() {
        Object ref = energyCode_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          energyCode_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string energyCode = 1;</code>
       */
      public com.google.protobuf.ByteString
          getEnergyCodeBytes() {
        Object ref = energyCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          energyCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string energyCode = 1;</code>
       */
      public Builder setEnergyCode(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        energyCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string energyCode = 1;</code>
       */
      public Builder clearEnergyCode() {
        
        energyCode_ = getDefaultInstance().getEnergyCode();
        onChanged();
        return this;
      }
      /**
       * <code>string energyCode = 1;</code>
       */
      public Builder setEnergyCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        energyCode_ = value;
        onChanged();
        return this;
      }

      private Object regionCode_ = "";
      /**
       * <code>string regionCode = 2;</code>
       */
      public String getRegionCode() {
        Object ref = regionCode_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          regionCode_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string regionCode = 2;</code>
       */
      public com.google.protobuf.ByteString
          getRegionCodeBytes() {
        Object ref = regionCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          regionCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string regionCode = 2;</code>
       */
      public Builder setRegionCode(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        regionCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string regionCode = 2;</code>
       */
      public Builder clearRegionCode() {
        
        regionCode_ = getDefaultInstance().getRegionCode();
        onChanged();
        return this;
      }
      /**
       * <code>string regionCode = 2;</code>
       */
      public Builder setRegionCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        regionCode_ = value;
        onChanged();
        return this;
      }

      private Object industryCode_ = "";
      /**
       * <code>string industryCode = 3;</code>
       */
      public String getIndustryCode() {
        Object ref = industryCode_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          industryCode_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string industryCode = 3;</code>
       */
      public com.google.protobuf.ByteString
          getIndustryCodeBytes() {
        Object ref = industryCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          industryCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string industryCode = 3;</code>
       */
      public Builder setIndustryCode(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        industryCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string industryCode = 3;</code>
       */
      public Builder clearIndustryCode() {
        
        industryCode_ = getDefaultInstance().getIndustryCode();
        onChanged();
        return this;
      }
      /**
       * <code>string industryCode = 3;</code>
       */
      public Builder setIndustryCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        industryCode_ = value;
        onChanged();
        return this;
      }

      private Object domainCode_ = "";
      /**
       * <code>string domainCode = 4;</code>
       */
      public String getDomainCode() {
        Object ref = domainCode_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          domainCode_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string domainCode = 4;</code>
       */
      public com.google.protobuf.ByteString
          getDomainCodeBytes() {
        Object ref = domainCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          domainCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string domainCode = 4;</code>
       */
      public Builder setDomainCode(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        domainCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string domainCode = 4;</code>
       */
      public Builder clearDomainCode() {
        
        domainCode_ = getDefaultInstance().getDomainCode();
        onChanged();
        return this;
      }
      /**
       * <code>string domainCode = 4;</code>
       */
      public Builder setDomainCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        domainCode_ = value;
        onChanged();
        return this;
      }

      private Object dataCode_ = "";
      /**
       * <code>string dataCode = 5;</code>
       */
      public String getDataCode() {
        Object ref = dataCode_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          dataCode_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string dataCode = 5;</code>
       */
      public com.google.protobuf.ByteString
          getDataCodeBytes() {
        Object ref = dataCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          dataCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string dataCode = 5;</code>
       */
      public Builder setDataCode(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        dataCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string dataCode = 5;</code>
       */
      public Builder clearDataCode() {
        
        dataCode_ = getDefaultInstance().getDataCode();
        onChanged();
        return this;
      }
      /**
       * <code>string dataCode = 5;</code>
       */
      public Builder setDataCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        dataCode_ = value;
        onChanged();
        return this;
      }

      private double dataValue_ ;
      /**
       * <code>double dataValue = 6;</code>
       */
      public double getDataValue() {
        return dataValue_;
      }
      /**
       * <code>double dataValue = 6;</code>
       */
      public Builder setDataValue(double value) {
        
        dataValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double dataValue = 6;</code>
       */
      public Builder clearDataValue() {
        
        dataValue_ = 0D;
        onChanged();
        return this;
      }

      private long dataTime_ ;
      /**
       * <code>int64 dataTime = 7;</code>
       */
      public long getDataTime() {
        return dataTime_;
      }
      /**
       * <code>int64 dataTime = 7;</code>
       */
      public Builder setDataTime(long value) {
        
        dataTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 dataTime = 7;</code>
       */
      public Builder clearDataTime() {
        
        dataTime_ = 0L;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:msg.EnergyData)
    }

    // @@protoc_insertion_point(class_scope:msg.EnergyData)
    private static final EnergyData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new EnergyData();
    }

    public static EnergyData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EnergyData>
        PARSER = new com.google.protobuf.AbstractParser<EnergyData>() {
      @Override
      public EnergyData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EnergyData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<EnergyData> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<EnergyData> getParserForType() {
      return PARSER;
    }

    @Override
    public EnergyData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_msg_EnergyData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_msg_EnergyData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\017EnergyDws.proto\022\003msg\"\225\001\n\nEnergyData\022\022\n" +
      "\nenergyCode\030\001 \001(\t\022\022\n\nregionCode\030\002 \001(\t\022\024\n" +
      "\014industryCode\030\003 \001(\t\022\022\n\ndomainCode\030\004 \001(\t\022" +
      "\020\n\010dataCode\030\005 \001(\t\022\021\n\tdataValue\030\006 \001(\001\022\020\n\010" +
      "dataTime\030\007 \001(\003B\024\n\022com.smxknife.hbaseb\006pr" +
      "oto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_msg_EnergyData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_msg_EnergyData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_msg_EnergyData_descriptor,
        new String[] { "EnergyCode", "RegionCode", "IndustryCode", "DomainCode", "DataCode", "DataValue", "DataTime", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
